version: '3.1'
services:
  redis:
    container_name: maha-redis
    image: 'redis'
    ports: ['6379:6379']
  db:
    container_name: maha-db
    env_file:
      - ./.env.local
    image: 'postgres'
    ports: ['5432:5432']
    restart: always
  authn-migrate:
    command: './authn migrate'
    container_name: maha-authn-migrate
    env_file:
      - ./.env.local
    image: 'keratin/authn-server:1.10.4'
    depends_on:
      - redis
      - db
  authn:
    container_name: maha-authn
    env_file:
      - ./.env.local
    image: 'keratin/authn-server:1.10.4'
    ports: ['3001:3000']
    depends_on:
      - authn-migrate
      - redis
      - db
