export enum OrganizationPageType {
  AddProperty = 'AddProperty',
  DynamicRoute = 'DynamicRoute',
  EditProperty = 'EditProperty',
  Insights = 'Insights',
  Members = 'Members',
  Overview = 'Overview',
  Properties = 'Properties',
  Roles = 'Roles',
  Sales = 'Sales',
  SalesLeads = 'SalesLeads',
  SalesVisits = 'SalesVisits',
  SalesReservations = 'SalesReservations',
  SalesClosures = 'SalesClosures',
}
